global:
  scrape_interval:     15s  # How frequently to scrape targets (default is every 1 minute)
  evaluation_interval: 15s  # How frequently to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Replace with the address and port of your Prometheus server

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # Replace with the address and port of your Node Exporter instance

  # Add additional scrape configurations as needed for other services

